version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 35
    labels:
      - dependencies
      - dependencies::go
    assignees:
      - joelMuehlena
    reviewers:
      - joelMuehlena
    commit-message:
      prefix: deps
      include: scope
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - dependencies::gh-actions
    assignees:
      - joelMuehlena
    reviewers:
      - joelMuehlena
    commit-message:
      prefix: deps
      include: scope

