stages:
  - publish

publish-provider-to-github:
  stage: publish
  image: alpine:3.20
  before_script:
    - apk update
    - apk add rsync git
  script:
    - git config --global credential.helper store
    - echo https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com > ~/.git-credentials
    - git config --global user.email "$GITHUB_USERNAME"
    - git config --global user.name "Joel Mühlena"
    - git clone https://github.com/joelMuehlena/terraform-provider-pdns.git terraform-provider-pdns-GITHUB
    - rsync -av --progress code/terraform/provider/terraform-provider-pdns/ terraform-provider-pdns-GITHUB/
    - cd terraform-provider-pdns-GITHUB
    - git add .
    - git commit -m "New changed from upstream. Look there for more info"
    - git push
  rules:
    - changes:
        - code/terraform/provider/terraform-provider-pdns/*
        - code/terraform/provider/terraform-provider-pdns/**/*
